apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-app
  namespace: monitoring

data:
  MYSQL_DATABASE: "zabbix"
  MYSQL_USER: "zabbix"
  ZBX_SERVER_NAME: "zabbix"
  ZBX_SERVER_HOST: "zabbix-server"
  DB_SERVER_HOST: "mysql-server"
  PHP_TZ: "Europe/Paris"
  ZBX_HOSTNAME: "Zabbix server"
  ZBX_DEBUGLEVEL: "4"
  ZBX_CACHESIZE: "1024M"
  ZBX_AUTOHANODENAME: "fqdn"
  ZBX_AUTONODEADDRESS: "fqdn"
  ZBX_SERVICEMANAGERSYNCFREQUENCY: "10"
  ZBX_PROBLEMHOUSEKEEPINGFREQUENCY: "60" 
