apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: zabbix
  name: zabbix-agent
  labels:
    app: zabbix-agent
spec:
  selector:
   matchLabels:
    name: zabbix-agent
  updateStrategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 1
  template:
    metadata:
      labels:
        name: zabbix-agent
        app: zabbix-agent
    spec:
      hostNetwork: true
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-6.2-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10050
            name: zabbix-agent
          env:
            - name: ZBX_DEBUGLEVEL
              value: "5"
            - name: ZBX_DENYKEY
              value: "system.run[*]"
            - name: ZBX_LOGREMOTECOMMANDS
              value: "1"
            - name: ZBX_PASSIVE_ALLOW
              value: "true"
            - name: ZBX_ACTIVE_ALLOW
              value: "true"
            - name: ZBX_UNSAFEUSERPARAMETERS
              value: "0"
            - name: DEBUG_MODE
              value: "3"
      
            - name: ZBX_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: ZBX_HOSTNAME
                  name: dbconfig
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: ZBX_SERVER_HOST
                  name: dbconfig

          volumeMounts:
          - mountPath: /etc/zabbix/zabbix_agentd.d
            name: zabbix-agent-claim2
            readOnly: true
      volumes:
      - name: zabbix-agent-claim2
        persistentVolumeClaim:
          claimName: zabbix-agent-claim2
          readOnly: true

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: zabbix
  creationTimestamp: null
  labels:
     zabbix-app: zabbix-agent
  name: zabbix-agent-claim2
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
