apiVersion: v1
kind: Service
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix-java-gateway
  namespace: monitoring
spec:
  ports:
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx
  selector:
    name: zabbix-java-gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix-java-gateway
    tier: java
  namespace: monitoring
spec:
  selector:
    matchLabels:
     name: zabbix-java-gateway
     app: zabbix-java-gateway
  template:
    metadata:
      labels:
        name: zabbix-java-gateway
        app: zabbix-java-gateway
    spec:
      containers:
        - name: zabbix-java-gateway
          image: zabbix/zabbix-java-gateway:alpine-6.2-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10052
            protocol: TCP
            name: zabbix-java
          livenessProbe:
            tcpSocket:
              port: 10052
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 2
          env:
          - name: ZBX_START_POLLERS
            value: "5"
          - name: ZBX_TIMEOUT
            value: "3"
          - name: ZBX_DEBUGLEVEL
            value: "info"
          - name: JAVA_OPTIONS
            value: ""
          - name: DEBUG_MODE
            value: "false"
          securityContext:
            capabilities: {}
            privileged: false
