apiVersion: apps/v1
kind: StatefulSet

metadata:
  namespace: zabbix
  name: zabbix-server
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  serviceName: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - image: zabbix/zabbix-server-mysql:alpine-6.2-latest
          name: zabbix-server
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: dbconfig
                  
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key:  MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key:  MYSQL_PASSWORD
                  
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: ZBX_SERVER_HOST
                  name: dbconfig

            - name: DB_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER_HOST
                  name: dbconfig
        
            - name: DB_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER_PORT
                  name: dbconfig
              
            - name: ZBX_JAVAGATEWAY
              valueFrom:
                configMapKeyRef:
                  key: ZBX_JAVAGATEWAY
                  name: dbconfig
           
          ports:
            - containerPort: 10051
              name: zabbix-server
          volumeMounts:
            - name: zabbix-server-storage
              mountPath: /var/lib/zabbix/
      volumes:
        - name: zabbix-server-storage
          persistentVolumeClaim:
            claimName: server-pv-claim

    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: zabbix
  name: server-pv-claim
  labels:
    app: zabbix-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  namespace: zabbix
  name: zabbix-server
  labels:
    app: zabbix-server
spec:
  selector:
    app: zabbix-server
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: zabbix-server
    port: 10051
    targetPort: 10051
