apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  selector:
    matchLabels:
      app: zabbix-web
  serviceName: "zabbix-web"
  replicas: 1 
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - image: zabbix/zabbix-web-nginx-mysql:alpine-6.2-latest
        name: zabbix-web
        ports:
        - containerPort: 8080
          protocol: TCP
          name: web-http
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: MYSQL_DATABASE
                name: dbconfig
              
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: mysecret

          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: mysecret
        
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key:  MYSQL_USER
                name: mysecret

          - name: ZBX_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                key: ZBX_SERVER_HOST
                name: dbconfig

          - name: DB_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                key: DB_SERVER_HOST
                name: dbconfig

          - name: TZ
            value: "Europe/Paris"
          - name: PHP_TZ
            value: "Europe/Paris"

        resources: {}
---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: zabbix
  labels:
    app: zabbix
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: web-http
    - port: 443
      targetPort: 8443
      name: web-https
  selector:
    app: zabbix-web
  type: NodePort
